from django.urls import path
from . import views

app_name = "inventory"

urlpatterns = [
    path("", views.index, name="index"),
    path("signup/", views.SignUpView.as_view(), name="signup"),
    path("login/", views.LoginView.as_view(), name="login"),
    path("logout/", views.LogoutView.as_view(), name="logout"),
    path("marcas/", views.MarcaListView.as_view(), name="marca_list"),
    path("marcas/nueva/", views.MarcaCreateView.as_view(), name="marca_create"),
    path("marcas/<int:pk>/", views.MarcaDetailView.as_view(), name="marca_detail"),
    path("marcas/<int:pk>/editar/", views.MarcaUpdateView.as_view(), name="marca_edit"),
    path("marcas/<int:pk>/borrar/", views.MarcaDeleteView.as_view(), name="marca_delete"),
    path("productos/", views.ProductoListView.as_view(), name="producto_list"),
    path("productos/nuevo/", views.ProductoCreateView.as_view(), name="producto_create"),
    path("productos/<int:pk>/", views.ProductoDetailView.as_view(), name="producto_detail"),
    path("productos/<int:pk>/editar/", views.ProductoUpdateView.as_view(), name="producto_update"),
    path("productos/<int:pk>/borrar/", views.ProductoDeleteView.as_view(), name="producto_delete"),
    path("set-local/", views.SetLocalView.as_view(), name="set_local"),
    path("articulos/", views.ArticuloListView.as_view(), name="articulo_list"),
    path("articulos/nuevo/", views.ArticuloCreateView.as_view(), name="articulo_create"),
    path("articulos/lookup/", views.ArticuloLookupByBarcodeView.as_view(), name="articulo_lookup"),
    path("articulos/<int:articulo_id>/editar/", views.ArticuloUpdateView.as_view(), name="articulo_edit"),
    path("articulos/<int:articulo_id>/baja/", views.ArticuloBajaView.as_view(), name="articulo_baja"),
    path("pos/", views.POSView.as_view(), name="pos"),
    path("pos/retirar-efectivo/", views.POSCajaView.as_view(), name="pos_caja"),
    path("pos/add/", views.POSAddItemByBarcodeView.as_view(), name="pos_add"),
    path("pos/remove/", views.POSRemoveItemView.as_view(), name="pos_remove"),
    path("pos/clear/", views.POSClearView.as_view(), name="pos_clear"),
    path("pos/checkout/", views.POSCheckoutView.as_view(), name="pos_checkout"),
    path("movimientos/", views.MovimientoStockView.as_view(), name="movimientos"),
    path("movimientos/pdf/", views.movimiento_pdf, name="movimientos_pdf"),
    path("ventas/<int:venta_id>/", views.VentaDetailView.as_view(), name="venta_detail"),
    path("ventas/<int:venta_id>/pdf/", views.venta_pdf, name="venta_pdf"),
    path("ingresos/<int:ingreso_id>/", views.IngresoDetailView.as_view(), name="ingreso_detail"),
    path("ingresos/<int:ingreso_id>/pdf/", views.ingreso_pdf, name="ingreso_pdf"),
    path("transferencias/<int:transferencia_id>/",views.TransferenciaDetailView.as_view(),name="transferencia_detail"),
    path("articulos/transferir/", views.ArticulosTransferirView.as_view(), name="articulos_transferir"),
    path("articulos/import-excel/", views.ArticuloImportXlsxView.as_view(), name="articulo_import_excel"),
    path("articulos/bulk-edit-form/", views.ArticulosBulkEditView.as_view(), name="articulo_bulk_edit_form"),
    path("articulos/bulk-baja/", views.ArticulosBulkBajaView.as_view(), name="articulos_bulk_baja"),
    path("bajas/<int:baja_id>/", views.BajaDetailView.as_view(), name="baja_detail"),
    path("productos/ajuste-marca/preview/", views.ProductoBulkAdjustPreviewView.as_view(), name="producto_bulk_marca_preview"),
    path("productos/ajuste-marca/apply/", views.ProductoBulkAdjustApplyView.as_view(), name="producto_bulk_marca_apply"),
    path("productos/ajuste-marca/undo/<int:adjust_id>/", views.ProductoBulkAdjustUndoView.as_view(), name="producto_bulk_marca_undo"),
    path("promociones/", views.PromocionListView.as_view(), name="promocion_list"),
    path("promociones/nueva/", views.PromocionCreateView.as_view(), name="promocion_create"),
    path("promociones/<int:promocion_id>/", views.PromocionDetailView.as_view(), name="promocion_detail"),
    path("promociones/<int:promocion_id>/editar/", views.PromocionUpdateView.as_view(), name="promocion_edit"),
    path("promociones/<int:promocion_id>/toggle/", views.PromocionToggleEstadoView.as_view(), name="promocion_toggle"),
    path("promociones/<int:promocion_id>/delete/", views.PromocionDeleteView.as_view(), name="promocion_delete"),
    path("pos/resumen-dia/pdf/", views.pos_resumen_dia_pdf, name="pos_resumen_dia_pdf"),
    path("productos/importar-excel/", views.ProductoImportXlsxView.as_view(),name="producto_import_excel"),
]
