# Generated by Django 6.0.1 on 2026-02-04 17:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('product_id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
                ('tipo_producto', models.CharField(max_length=100)),
                ('material', models.CharField(max_length=100)),
                ('marca', models.CharField(max_length=100)),
                ('precio', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name='Articulo',
            fields=[
                ('articulo_id', models.AutoField(primary_key=True, serialize=False)),
                ('barcode', models.CharField(db_index=True, max_length=100)),
                ('sku', models.CharField(max_length=100)),
                ('talle', models.IntegerField()),
                ('color', models.CharField(max_length=50)),
                ('estado', models.CharField(choices=[('DISP', 'Disponible'), ('VEND', 'Vendido'), ('BAJA', 'Baja')], db_index=True, default='DISP', max_length=4)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('product_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.producto')),
            ],
            options={
                'indexes': [models.Index(fields=['barcode'], name='inventory_a_barcode_83345f_idx'), models.Index(fields=['sku'], name='inventory_a_sku_18cbbb_idx')],
            },
        ),
    ]
