# Generated by Django 6.0.1 on 2026-01-27 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_articulo'),
    ]

    operations = [
        migrations.AddField(
            model_name='articulo',
            name='barcode',
            field=models.CharField(db_index=True, default=123, max_length=100),
            preserve_default=False,
        ),
        migrations.AddIndex(
            model_name='articulo',
            index=models.Index(fields=['barcode'], name='inventory_a_barcode_83345f_idx'),
        ),
        migrations.AddIndex(
            model_name='articulo',
            index=models.Index(fields=['sku'], name='inventory_a_sku_18cbbb_idx'),
        ),
    ]
