# Generated by Django 6.0.1 on 2026-02-05 16:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0003_local_ingreso_ingresoitem_articulo_ingreso_item'),
    ]

    operations = [
        migrations.AddField(
            model_name='articulo',
            name='local',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='inventory.local'),
        ),
        migrations.AddField(
            model_name='ingreso',
            name='local',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='inventory.local'),
        ),
        migrations.AddField(
            model_name='venta',
            name='local',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='inventory.local'),
        ),
        migrations.AlterField(
            model_name='ventaarticulo',
            name='articulo',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to='inventory.articulo'),
        ),
    ]
