# Generated by Django 6.0.1 on 2026-02-06 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0004_articulo_local_ingreso_local_venta_local_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='venta',
            name='metodo_de_pago',
            field=models.CharField(choices=[('EFEC', 'Efectivo'), ('TARJ', 'Tarjeta'), ('TRANS', 'Transferencia'), ('OTRO', 'Otro')], db_index=True, default='EFEC', max_length=15),
        ),
    ]
