# Generated by Django 6.0.1 on 2026-02-06 20:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0005_venta_metodo_de_pago'),
    ]

    operations = [
        migrations.AddField(
            model_name='venta',
            name='profit_total',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=12),
        ),
    ]
