# Generated by Django 6.0.1 on 2026-02-06 21:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0006_venta_profit_total'),
    ]

    operations = [
        migrations.AddField(
            model_name='ventaitem',
            name='costo_unitario',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='ventaitem',
            name='profit_linea',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
    ]
