# Generated by Django 6.0.1 on 2026-02-06 21:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0007_ventaitem_costo_unitario_ventaitem_profit_linea'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MovimientoStock',
            fields=[
                ('movimiento_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('fecha', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('tipo', models.CharField(choices=[('IN', 'Ingreso'), ('OUT', 'Venta'), ('ADJ', 'Ajuste'), ('TRF', 'Transferencia'), ('BAJ', 'Baja'), ('RET', 'Devolución')], db_index=True, max_length=3)),
                ('sku', models.CharField(db_index=True, max_length=100)),
                ('talle', models.IntegerField()),
                ('color', models.CharField(max_length=50)),
                ('cantidad', models.IntegerField()),
                ('costo_unitario', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('precio_unitario', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('profit_unitario', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('nota', models.TextField(blank=True)),
                ('articulo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='movimientos', to='inventory.articulo')),
                ('ingreso', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='inventory.ingreso')),
                ('local', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='inventory.local')),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='inventory.producto')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('venta', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='inventory.venta')),
            ],
            options={
                'ordering': ['-fecha', '-movimiento_id'],
                'indexes': [models.Index(fields=['local', 'fecha'], name='inventory_m_local_i_31ea13_idx'), models.Index(fields=['tipo', 'fecha'], name='inventory_m_tipo_31b222_idx'), models.Index(fields=['producto'], name='inventory_m_product_69f0ad_idx')],
            },
        ),
    ]
