# Generated by Django 6.0.1 on 2026-02-09 21:45

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0008_movimientostock'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='movimientostock',
            name='barcode',
            field=models.CharField(db_index=True, default=12345, max_length=100),
            preserve_default=False,
        ),
        migrations.AddIndex(
            model_name='movimientostock',
            index=models.Index(fields=['barcode'], name='inventory_m_barcode_f73420_idx'),
        ),
        migrations.AddIndex(
            model_name='movimientostock',
            index=models.Index(fields=['venta'], name='inventory_m_venta_i_72f5be_idx'),
        ),
        migrations.AddIndex(
            model_name='movimientostock',
            index=models.Index(fields=['ingreso'], name='inventory_m_ingreso_79daed_idx'),
        ),
    ]
