# Generated by Django 6.0.1 on 2026-02-13 18:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0011_alter_venta_fecha'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='movimientostock',
            name='local_destino',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='movs_destino', to='inventory.local'),
        ),
        migrations.AddField(
            model_name='movimientostock',
            name='local_origen',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='movs_origen', to='inventory.local'),
        ),
        migrations.CreateModel(
            name='Transferencia',
            fields=[
                ('transferencia_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('fecha', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('nota', models.TextField(blank=True)),
                ('local_destino', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='transferencias_entrantes', to='inventory.local')),
                ('local_origen', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='transferencias_salientes', to='inventory.local')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='movimientostock',
            name='transferencia',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='inventory.transferencia'),
        ),
        migrations.CreateModel(
            name='TransferenciaItem',
            fields=[
                ('item_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('sku', models.CharField(max_length=100)),
                ('barcode', models.CharField(db_index=True, max_length=100)),
                ('talle', models.IntegerField()),
                ('color', models.CharField(max_length=50)),
                ('articulo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='inventory.articulo')),
                ('transferencia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='inventory.transferencia')),
            ],
        ),
    ]
