# Generated by Django 6.0.1 on 2026-02-23 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0012_movimientostock_local_destino_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ingresoitem',
            name='costo_unitario',
        ),
        migrations.AddField(
            model_name='producto',
            name='costo',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
