# Generated by Django 6.0.1 on 2026-02-23 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0013_remove_ingresoitem_costo_unitario_producto_costo'),
    ]

    operations = [
        migrations.AddField(
            model_name='ingresoitem',
            name='costo_unitario',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='producto',
            name='costo',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
