# Generated by Django 6.0.2 on 2026-03-03 15:21

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0016_bajastock_movimientostock_baja'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='movimientostock',
            name='tipo',
            field=models.CharField(choices=[('IN', 'Ingreso'), ('OUT', 'Venta'), ('TRF', 'Transferencia'), ('BAJ', 'Baja'), ('RET', 'Devolución')], db_index=True, max_length=3),
        ),
        migrations.CreateModel(
            name='RetiroCaja',
            fields=[
                ('retiro_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('fecha', models.DateField(db_index=True, default=django.utils.timezone.localdate)),
                ('monto', models.DecimalField(decimal_places=2, max_digits=12)),
                ('motivo', models.CharField(choices=[('GUARDAR', 'Guardar (dueño)'), ('GASTO', 'Gasto del día'), ('OTRO', 'Otro')], default='GUARDAR', max_length=16)),
                ('nota', models.CharField(blank=True, max_length=140)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('local', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='retiros_caja', to='inventory.local')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='retiros_caja', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-creado_en'],
                'indexes': [models.Index(fields=['local', 'fecha'], name='inventory_r_local_i_d0c152_idx')],
            },
        ),
    ]
