# Generated by Django 6.0.2 on 2026-03-04 21:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0017_alter_movimientostock_tipo_retirocaja'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductoBulkAdjust',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('pct_precio', models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True)),
                ('pct_costo', models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True)),
                ('afectados', models.PositiveIntegerField(default=0)),
                ('estado', models.CharField(choices=[('APLICADO', 'Aplicado'), ('DESHECHO', 'Deshecho')], default='APLICADO', max_length=16)),
                ('note', models.CharField(blank=True, default='', max_length=160)),
                ('marca', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='inventory.marca')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ProductoBulkAdjustItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('old_precio', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('old_costo', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('new_precio', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('new_costo', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('adjust', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='inventory.productobulkadjust')),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='inventory.producto')),
            ],
            options={
                'unique_together': {('adjust', 'producto')},
            },
        ),
    ]
