# Generated by Django 6.0.2 on 2026-03-06 16:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0018_productobulkadjust_productobulkadjustitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='ventaitem',
            name='descuento_unitario',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='ventaitem',
            name='precio_base_unitario',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=12),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='ventaitem',
            name='promocion_nombre',
            field=models.CharField(blank=True, default='', max_length=120),
        ),
        migrations.CreateModel(
            name='Promocion',
            fields=[
                ('promocion_id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=120)),
                ('descripcion', models.TextField(blank=True, max_length=255)),
                ('estado', models.CharField(choices=[('ACT', 'Activa'), ('PAU', 'Pausada')], default='ACT', max_length=3)),
                ('tipo_descuento', models.CharField(choices=[('PCT', 'Porcentaje'), ('FIX', 'Monto fijo')], max_length=3)),
                ('valor', models.DecimalField(decimal_places=2, max_digits=10)),
                ('fecha_inicio', models.DateTimeField(blank=True, null=True)),
                ('fecha_fin', models.DateTimeField(blank=True, null=True)),
                ('prioridad', models.IntegerField(default=0)),
                ('aplica_a_todos', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('marcas', models.ManyToManyField(blank=True, related_name='promociones', to='inventory.marca')),
                ('productos', models.ManyToManyField(blank=True, related_name='promociones', to='inventory.producto')),
            ],
        ),
        migrations.AddField(
            model_name='ventaitem',
            name='promocion',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='inventory.promocion'),
        ),
    ]
