# Generated by Django 6.0.2 on 2026-03-10 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0019_ventaitem_descuento_unitario_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='venta',
            name='total_descuento',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
    ]
