# Generated by Django 6.0.2 on 2026-03-10 21:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0020_venta_total_descuento'),
    ]

    operations = [
        migrations.AddField(
            model_name='promocion',
            name='descuento_porcentaje',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='promocion',
            name='unidad_objetivo',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='promocion',
            name='tipo_descuento',
            field=models.CharField(choices=[('PCT', 'Porcentaje'), ('FIX', 'Monto fijo'), ('ESC', 'Descuento por unidad escalonada')], max_length=3),
        ),
        migrations.AlterField(
            model_name='promocion',
            name='valor',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
