# Generated by Django 6.0.2 on 2026-03-16 21:08

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0021_promocion_descuento_porcentaje_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='retirocaja',
            name='tipo',
            field=models.CharField(choices=[('SALIDA', 'Salida'), ('ENTRADA', 'Entrada')], db_index=True, default='SALIDA', max_length=10),
        ),
        migrations.AlterField(
            model_name='retirocaja',
            name='motivo',
            field=models.CharField(choices=[('GUARDAR', 'Guardar (dueño)'), ('GASTO', 'Gasto del día'), ('APORTE', 'Aporte de caja'), ('AJUSTE', 'Ajuste'), ('OTRO', 'Otro')], default='GUARDAR', max_length=16),
        ),
        migrations.AddIndex(
            model_name='retirocaja',
            index=models.Index(fields=['local', 'tipo'], name='inventory_r_local_i_4ca6f4_idx'),
        ),
    ]
