# Generated by Django 6.0.2 on 2026-03-26 13:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0022_retirocaja_tipo_alter_retirocaja_motivo_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Devolucion',
            fields=[
                ('devolucion_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('fecha', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('estado', models.CharField(choices=[('ABI', 'Abierta'), ('CER', 'Cerrada'), ('ANU', 'Anulada')], default='ABI', max_length=3)),
                ('credito_total', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('total_nuevo', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('diferencia_cobrada', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('nota', models.TextField(blank=True, default='')),
                ('local', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='inventory.local')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('venta_origen', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='devoluciones', to='inventory.venta')),
            ],
        ),
        migrations.CreateModel(
            name='DevolucionItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sku', models.CharField(max_length=120)),
                ('barcode', models.CharField(max_length=120)),
                ('talle', models.IntegerField()),
                ('color', models.CharField(max_length=80)),
                ('precio_reconocido', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('articulo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='inventory.articulo')),
                ('devolucion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items_devueltos', to='inventory.devolucion')),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='inventory.producto')),
                ('venta_item', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='inventory.ventaitem')),
            ],
        ),
        migrations.CreateModel(
            name='DevolucionSalidaItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sku', models.CharField(max_length=120)),
                ('barcode', models.CharField(max_length=120)),
                ('talle', models.IntegerField()),
                ('color', models.CharField(max_length=80)),
                ('precio_unitario', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('articulo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='inventory.articulo')),
                ('devolucion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items_entregados', to='inventory.devolucion')),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='inventory.producto')),
            ],
        ),
    ]
